import os

files = {
    ".env.local": "NEXT_PUBLIC_API_URL=http://127.0.0.1:8000/api/v1",
    "src/types/api.d.ts": "export interface TokenResponse {\n  access_token: string;\n  refresh_token: string;\n  token_type: string;\n}\n\nexport interface TokenPayload {\n  sub: string;\n  tenant_id: string;\n  role: string;\n  exp: number;\n}",
    "src/lib/api-client.ts": "import axios from 'axios';\nimport { useAuthStore } from '@/store/authStore';\n\nexport const apiClient = axios.create({\n  baseURL: process.env.NEXT_PUBLIC_API_URL,\n  headers: {\n    'Content-Type': 'application/json',\n  },\n});\n\napiClient.interceptors.request.use((config) => {\n  const token = useAuthStore.getState().accessToken;\n  if (token) {\n    config.headers.Authorization = `Bearer ${token}`;\n  }\n  return config;\n});",
    "src/store/authStore.ts": "import { create } from 'zustand';\nimport { persist } from 'zustand/middleware';\nimport { jwtDecode } from 'jwt-decode';\nimport { TokenPayload } from '@/types/api';\n\ninterface AuthState {\n  accessToken: string | null;\n  refreshToken: string | null;\n  user: TokenPayload | null;\n  setTokens: (access: string, refresh: string) => void;\n  logout: () => void;\n}\n\nexport const useAuthStore = create<AuthState>()(\n  persist(\n    (set) => ({\n      accessToken: null,\n      refreshToken: null,\n      user: null,\n      setTokens: (access, refresh) => {\n        const decoded = jwtDecode<TokenPayload>(access);\n        set({ accessToken: access, refreshToken: refresh, user: decoded });\n      },\n      logout: () => set({ accessToken: null, refreshToken: null, user: null }),\n    }),\n    {\n      name: 'auth-storage',\n    }\n  )\n);",
    "src/app/(auth)/login/page.tsx": "import { LoginForm } from '@/components/forms/LoginForm';\n\nexport default function LoginPage() {\n  return (\n    <div className=\"min-h-screen flex items-center justify-center bg-slate-50 p-4\">\n      <LoginForm />\n    </div>\n  );\n}",
    "src/components/forms/LoginForm.tsx": "'use client';\nimport { useState } from 'react';\nimport { useRouter } from 'next/navigation';\nimport { useAuthStore } from '@/store/authStore';\nimport { apiClient } from '@/lib/api-client';\nimport { Button } from '@/components/ui/button';\nimport { Input } from '@/components/ui/input';\nimport { Label } from '@/components/ui/label';\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';\n\nexport function LoginForm() {\n  const [domain, setDomain] = useState('system.local');\n  const [email, setEmail] = useState('admin@system.local');\n  const [password, setPassword] = useState('SuperSecurePassword123!');\n  const [error, setError] = useState('');\n  const [loading, setLoading] = useState(false);\n  const router = useRouter();\n  const setTokens = useAuthStore((state) => state.setTokens);\n\n  const handleLogin = async (e: React.FormEvent) => {\n    e.preventDefault();\n    setLoading(true);\n    setError('');\n    try {\n      const res = await apiClient.post('/auth/login', { domain, email, password });\n      setTokens(res.data.access_token, res.data.refresh_token);\n      router.push('/superadmin');\n    } catch (err: any) {\n      setError(err.response?.data?.detail || 'Authentication failed');\n    } finally {\n      setLoading(false);\n    }\n  };\n\n  return (\n    <Card className=\"w-full max-w-md mx-auto\">\n      <CardHeader>\n        <CardTitle>System Login</CardTitle>\n        <CardDescription>Enter credentials to access the ERP</CardDescription>\n      </CardHeader>\n      <CardContent>\n        <form onSubmit={handleLogin} className=\"space-y-4\">\n          <div className=\"space-y-2\">\n            <Label htmlFor=\"domain\">Tenant Domain</Label>\n            <Input id=\"domain\" value={domain} onChange={(e) => setDomain(e.target.value)} required />\n          </div>\n          <div className=\"space-y-2\">\n            <Label htmlFor=\"email\">Email Address</Label>\n            <Input id=\"email\" type=\"email\" value={email} onChange={(e) => setEmail(e.target.value)} required />\n          </div>\n          <div className=\"space-y-2\">\n            <Label htmlFor=\"password\">Password</Label>\n            <Input id=\"password\" type=\"password\" value={password} onChange={(e) => setPassword(e.target.value)} required />\n          </div>\n          {error && <p className=\"text-red-500 text-sm font-medium\">{error}</p>}\n          <Button type=\"submit\" className=\"w-full\" disabled={loading}>\n            {loading ? 'Authenticating...' : 'Sign In'}\n          </Button>\n        </form>\n      </CardContent>\n    </Card>\n  );\n}",
    "src/app/(dashboard)/superadmin/page.tsx": "'use client';\nimport { useAuthStore } from '@/store/authStore';\nimport { Button } from '@/components/ui/button';\nimport { useRouter } from 'next/navigation';\nimport { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';\n\nexport default function SuperAdminDashboard() {\n  const user = useAuthStore((state) => state.user);\n  const logout = useAuthStore((state) => state.logout);\n  const router = useRouter();\n\n  const handleLogout = () => {\n    logout();\n    router.push('/login');\n  };\n\n  return (\n    <div className=\"p-8 min-h-screen bg-slate-50\">\n      <Card className=\"max-w-2xl mx-auto\">\n        <CardHeader>\n          <CardTitle>Super Admin Interface</CardTitle>\n        </CardHeader>\n        <CardContent className=\"space-y-4\">\n          <div className=\"bg-slate-100 p-4 rounded-md\">\n            <p className=\"text-sm font-mono break-all\"><strong>Subject ID:</strong> {user?.sub}</p>\n            <p className=\"text-sm font-mono break-all\"><strong>Tenant ID:</strong> {user?.tenant_id}</p>\n            <p className=\"text-sm font-mono break-all\"><strong>Role ID:</strong> {user?.role}</p>\n          </div>\n          <Button onClick={handleLogout} variant=\"destructive\">Disconnect Session</Button>\n        </CardContent>\n      </Card>\n    </div>\n  );\n}",
    "src/app/page.tsx": "import { redirect } from 'next/navigation';\n\nexport default function Home() {\n  redirect('/login');\n}",
    "src/app/providers.tsx": "'use client';\nimport { QueryClient, QueryClientProvider } from '@tanstack/react-query';\nimport { useState } from 'react';\n\nexport default function Providers({ children }: { children: React.ReactNode }) {\n  const [queryClient] = useState(() => new QueryClient());\n  return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>;\n}",
    "src/app/layout.tsx": "import type { Metadata } from 'next';\nimport { Inter } from 'next/font/google';\nimport './globals.css';\nimport Providers from './providers';\n\nconst inter = Inter({ subsets: ['latin'] });\n\nexport const metadata: Metadata = {\n  title: 'School ERP',\n  description: 'Multi-tenant School Management System',\n};\n\nexport default function RootLayout({\n  children,\n}: Readonly<{\n  children: React.ReactNode;\n}>) {\n  return (\n    <html lang=\"en\">\n      <body className={inter.className}>\n        <Providers>{children}</Providers>\n      </body>\n    </html>\n  );\n}"
}

for path, content in files.items():
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

print("[+] UI files forcefully overwritten.")