"""fix_enrollment_columns

Revision ID: 6bb1f03eb5cd
Revises: f2ff89356be2
Create Date: 2026-07-16 23:44:48.703410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb1f03eb5cd'
down_revision: Union[str, Sequence[str], None] = 'f2ff89356be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
